#
# Author : Stefano Pallozzi
#
# https://travis-ci.org/
# https://docs.travis-ci.com/
# https://github.com/marketplace/travis-ci
#
language: php

php:
  - '7.3'
  - '7.4'
  - '8.0'
  - '8.1'


install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls