#
# Author : Stefano Pallozzi
#
# https://travis-ci.org/
# https://docs.travis-ci.com/
# https://github.com/marketplace/travis-ci
#
language: php

sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - '8.1'

cache:
  directories:
    - $HOME/.composer/cache
install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

before_script:
  - mkdir -p build/logs
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v